--- #YAML:1.0
name:                     qa-hackathon-website
version:                  1.03
abstract:                 The QA Hackathon Website
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        website

build_requires:
  ExtUtils::MakeMaker:    0
  IO::File:               0
  Test::More:             0.70
configure_requires:
  ExtUtils::MakeMaker:    0
requires:
  perl:                   5.006
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0

no_index:
  directory:
    - t

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: https://github.com/barbie/qa-hackathon-website/issues
  repository: http://github.com/barbie/qa-hackathon-website

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0

